### ISSUE TITLE
Allowing injector overrides?

### ISSUE THREAD

**Issue by bummzack** [markguinn/silverstripe-shop-search#6]
I was wondering if it might be a good idea to steer away from the `new Object` instantiation methods and use `Object::create` instead?

I'm not sure if it's a good idea to change all instantiations, maybe the `new ArrayList` and `new ArrayData` calls should remain as they are, since they are the most performance critical?

Instantiation of form-fields should probably be changed to the `::create` syntax.
What's your take on this?

**Comment by markguinn** [comment]
I agree fully. Anywhere you see a new that you think could be safely replaced feel free to do so.
