### ISSUE TITLE
Call to a member function Nice() on a non-object

### ISSUE THREAD

**Issue by adrian-stein** [markguinn/silverstripe-shop-search#8]
I am getting this error Fatal error:  <code>Call to a member function Nice() on a non-object in G:\Nimbler\ovesco\shop_search\code\ShopSearch.php on line 341</code>

https://github.com/markguinn/silverstripe-shop-search/blob/master/code/ShopSearch.php#L341

As <code>$prod->getPrice()</code> is being returned as a string instead of the casted currency. 

Can we do this to fix it up so it returns as the currency object?

<code>'price' => $prod->obj('Price')->Nice()</code>

I cant see how it may break things unless you know how other have implemented this module?

**Comment by markguinn** [comment]
That looks right. If you submit a PR I'll merge it.

**Comment by markguinn** [comment]
NM. I just made the change. Product does have a getPrice method, but ProductVariation doesn't. Are you searching variations?

**Comment by adrian-stein** [comment]
Thanks!!

No I am not using variations but it would cause an error for people who do. I had an old variation page type in my database when I was seeing if I wanted to use them so also know that variations cause an error on $prod->Link() as well.

I am not sure if you want to fix this now or leave a note or doc saying it is not 100% working with it or just let people figure it out on their own.

**Comment by markguinn** [comment]
Yeah, it's really not intended to search anything that doesn't have a link. I tend to add a "SearchCopy" field to products that includes text from variations or child products, etc and is only visible to Solr (or mysql fulltext). That makes variations searchable without the issue of linking to them. Thanks for pointing this out.
